/*
 * builders.h — see builders.c.
 *
 * The element-wise adapters are generated by the EW macro, so they are declared
 * here by the same list the macro is invoked with. A name here that no
 * invocation defines fails to LINK, which is the only way to keep a generated
 * set and a hand-written list in step.
 */
#ifndef PROMETHEUS_BUILDERS_H
#define PROMETHEUS_BUILDERS_H

#include "cast.h"
#include "crossentropy.h"
#include "dropout.h"
#include "elementwise.h"
#include "oracle.h"
#include "indexing.h"
#include "loop.h"
#include "mask.h"
#include "hmma.h"
#include "matmul.h"
#include "imma.h"
#include "normalize.h"
#include "optimizer.h"
#include "cpasync.h"
#include "reduction.h"
#include "residual.h"

unsigned bld_adamw(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_branch_nop(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_branch_nop_pred(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_branch_skip(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_causal(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_embedding(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_layer(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_loop_scale(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_masked_fill(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_matmul(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_imma(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_imma_gemm(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_imma_gemm2(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_imma_shared(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_cpasync_gemm(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_mean(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_rms(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_softmax(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_sum(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_transpose(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_copy(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_cpasync4(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_cpasync16(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_addidx(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_addconst(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_index(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_fadd(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_fmul(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_ffma(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_fneg(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_relu(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_exp2(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_log2(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_rcp(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_rsq(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_add(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_sub(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_mul(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_div(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_scale(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_exp(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_logn(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_sqrt(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_fill(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_clamp(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_addinp(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_silu(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_gelu(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_softcap(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_residual_rms(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_residual_dropout(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_cast_to_f16(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_cast_to_f32(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_dropout(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_cross_entropy(hp_word *p, NvU64 out, NvU64 in);
unsigned bld_slice(hp_word *p, NvU64 out, NvU64 in);

#endif /* PROMETHEUS_BUILDERS_H */
