/*
 * expect.h — the expected answers, declared.
 *
 * Generated by hand from the two expect_*.c files, and kept honest by the
 * compiler: the macros define these with external linkage, so a name here that
 * no file defines fails to link rather than failing quietly at run time.
 */
#ifndef PROMETHEUS_EXPECT_H
#define PROMETHEUS_EXPECT_H

#include "oracle.h"

const char *chk_adamw(const volatile NvU32 *o);
const char *chk_adamw_moments(const volatile NvU32 *m_out,
                              const volatile NvU32 *v_out);
const char *chk_add(const volatile NvU32 *o);
const char *chk_addconst(const volatile NvU32 *o);
const char *chk_addidx(const volatile NvU32 *o);
const char *chk_addinp(const volatile NvU32 *o);
const char *chk_branch_nop(const volatile NvU32 *o);
const char *chk_cast_to_f16(const volatile NvU32 *o);
const char *chk_cast_to_f32(const volatile NvU32 *o);
const char *chk_causal(const volatile NvU32 *o);
const char *chk_clamp(const volatile NvU32 *o);
const char *chk_copy(const volatile NvU32 *o);
const char *chk_cpasync(const volatile NvU32 *o);
const char *chk_div(const volatile NvU32 *o);
const char *chk_cross_entropy(const volatile NvU32 *o);
const char *chk_dropout(const volatile NvU32 *o);
const char *chk_embedding(const volatile NvU32 *o);
const char *chk_exp(const volatile NvU32 *o);
const char *chk_exp2(const volatile NvU32 *o);
const char *chk_fadd(const volatile NvU32 *o);
const char *chk_ffma(const volatile NvU32 *o);
const char *chk_fill(const volatile NvU32 *o);
const char *chk_fmul(const volatile NvU32 *o);
const char *chk_fneg(const volatile NvU32 *o);
const char *chk_gelu(const volatile NvU32 *o);
const char *chk_index(const volatile NvU32 *o);
const char *chk_layer(const volatile NvU32 *o);
const char *chk_loop_scale(const volatile NvU32 *o);
const char *chk_log2(const volatile NvU32 *o);
const char *chk_logn(const volatile NvU32 *o);
const char *chk_masked_fill(const volatile NvU32 *o);
const char *chk_matmul(const volatile NvU32 *o);
void pr_fill_imma(volatile NvU32 *a, volatile NvU32 *b);
const char *chk_imma(const volatile NvU32 *o);
const char *chk_mean(const volatile NvU32 *o);
const char *chk_mul(const volatile NvU32 *o);
const char *chk_ones(const volatile NvU32 *o);
const char *chk_rcp(const volatile NvU32 *o);
const char *chk_relu(const volatile NvU32 *o);
const char *chk_residual_dropout(const volatile NvU32 *o);
const char *chk_residual_rms(const volatile NvU32 *o);
const char *chk_rms(const volatile NvU32 *o);
const char *chk_rsq(const volatile NvU32 *o);
const char *chk_scale(const volatile NvU32 *o);
const char *chk_silu(const volatile NvU32 *o);
const char *chk_softcap(const volatile NvU32 *o);
const char *chk_slice(const volatile NvU32 *o);
const char *chk_softmax(const volatile NvU32 *o);
const char *chk_transpose(const volatile NvU32 *o);
const char *chk_sqrt(const volatile NvU32 *o);
const char *chk_sub(const volatile NvU32 *o);
const char *chk_sum(const volatile NvU32 *o);
const char *chk_zeros(const volatile NvU32 *o);

void pr_seed_addinp(volatile NvU32 *o);

#endif /* PROMETHEUS_EXPECT_H */
